
from scripts.sprint import sprint
from scripts.colors import ran, y, r, g, c
from subprocess import call
import time

print("\n" * 128)
print("                                                         ▄▄ ▄████▄▐▄▄▄▌           ")
print("            ▄▀▄     ▄▀▄                                 ▐  ████▀███▄█▄▌           ")
print("           ▄█░░▀▀▀▀▀░░█▄                              ▐ ▌  █▀▌  ▐▀▌▀█▀            ")
print("       ▄▄  █░░░░░░░░░░░█  ▄▄        //+++\\            ▀   ▌ ▌  ▐ ▌               ")
print("      █▄▄█ █░░▀░░┬░░▀░░█ █▄▄█      // |||  \\              █ █  ▐▌█               ")
print("██╗░░██╗██╗████████╗████████╗██╗░░░██╗|||████████╗░█████╗░░█████╗░██╗░░░░░░██████╗")
print("██║░██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗░██╔╝|||╚══██╔══╝██╔══██╗██╔══██╗██║░░░░░██╔════╝")
print("█████═╝░██║░░░██║░░░░░░██║░░░░╚████╔╝░|||░░░██║░░░██║░░██║██║░░██║██║░░░░░╚█████╗░")
print("██╔═██╗░██║░░░██║░░░░░░██║░░░░░╚██╔╝░░|||░░░██║░░░██║░░██║██║░░██║██║░░░░░░╚═══██╗")
print("██║░╚██╗██║░░░██║░░░░░░██║░░░░░░██║░░░|||░░░██║░░░╚█████╔╝╚█████╔╝███████╗██████╔╝")
print("╚═╝░░╚═╝╚═╝░░░╚═╝░░░░░░╚═╝░░░░░░╚═╝░░░|||░░░╚═╝░░░░╚════╝░░╚════╝░╚══════╝╚═════╝░")
print("Kahoot Hacks           \\             |||             //                          ")
print("                        \\            |||            //                           ")
print("                         \\           |||           //                            ")
print("                          \\          |||          //                             ")
print("                     /===================================\\                       ")
print("                   //                -Fun-                \\                      ")
print("                  ||                -Hacks-                ||                     ")
print("                  ||                 -For-                 ||                     ")
print("                  ||                 -The-                 ||                     ")
print("                  ||                -Whole-                ||                     ")
print("                   \\                -Family-             //                      ")
print("                    \\====================================/                       ")
print(" ")
print(f"{r}===========\\ ")
sprint(f"{r}NEWS: {y}HAPPY Valinines Day!!!{r} <3")
print(f"{r}===========// ")
print(" ")
print(" ")
print(" ")
time.sleep(2)
print(" ")
sprint(f"{g}Please type 1, 2, 3, or 4")
print(" ")
print("[1] How to use")
print("||| \\--------/")
print(" ")
print("[2] Information")
print("||| \\---------/")
print(" ")
print("[3] Flooder (Getting updated)")
print("||| \\-----/")
print(" ")
print(f"[4] {y}Start Hack")
print(f"{c}||| {g}\\--------/")
choice = input("")


if choice == "1":
    print(" ")
    print("Loading...")
    time.sleep(1)
    call(["python", "Kahoot/HTU.py"])

if choice == "2":
    print(" ")
    print("Loading...")
    time.sleep(1)
    call(["python", "Kahoot/Info.py"])

if choice == "3":
    print(" ")
    print("Loading...")
    time.sleep(1)
    call(["python", "Kahoot/flood/Info.py"])

if choice == "4":
    print(" ")
    print("Starting...")
    time.sleep(1)
    print("\n" * 64)  # imma this makes more sense
    call(["python", "Kahoot/kahoot.py"])

time.sleep(25)
print(" ")
print(" ")
print(" ")
print(" ")
print("Software Made by CPScript")
print(" ")
print("   ▄▀ ▄▀   ")
print("    ▀  ▀   ")
print("  █▀▀▀▀▀█▄ ")
print("  █░░░░░█ █")
print("  ▀▄▄▄▄▄▀▀ ")
