import time
from subprocess import call
# NEED TO MAKE LOOP... ill do this later
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("{INFO}")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("    ▄▄ ▄███████████████████████████████████████████▄▐▄▄▄▌           ")
print("   ▐  ████▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀███▄█▄▌           ")
print(" ▐ ▌  █▀▌                                         ▐▀▌▀█▀            ")
print("  ▀   ▌ ▌                                         ▐ ▌               ")
print("      █ █                                         ▐▌█               ")
print("""$$\   $$\          $$\                            $$\     
$$ | $$  |         $$ |                           $$ |    
$$ |$$  / $$$$$$\  $$$$$$$\   $$$$$$\   $$$$$$\ $$$$$$\   
$$$$$  /  \____$$\ $$  __$$\ $$  __$$\ $$  __$$\\_$$  _|  
$$  $$<   $$$$$$$ |$$ |  $$ |$$ /  $$ |$$ /  $$ | $$ |    
$$ |\$$\ $$  __$$ |$$ |  $$ |$$ |  $$ |$$ |  $$ | $$ |$$\ 
$$ | \$$\\$$$$$$$ |$$ |  $$ |\$$$$$$  |\$$$$$$  | \$$$$  |
\__|  \__|\_______|\__|  \__| \______/  \______/   \____/ 
""")
print("INFORMATION:")
print(" ")
print("""╔═╗┌┐ ┌─┐┬ ┬┌┬┐
╠═╣├┴┐│ ││ │ │ 
╩ ╩└─┘└─┘└─┘ ┴ 
""")
print("This tool, was made to help people Cheat on quizes... I always see fake cheats so i made a real one <3")
print(" ")
print(" ")
print("""╦ ╦┌─┐┌┬┐┌─┐┌┬┐┌─┐┌─┐
║ ║├─┘ ││├─┤ │ ├┤ └─┐
╚═╝┴  ─┴┘┴ ┴ ┴ └─┘└─┘
""")
print("1.5.7 = Made everything Look Cleaner")
print(" ")
print(" ")
print("""╔═╗┌─┐┌─┐┌┐┌  ╦ ╦┌─┐┌┬┐┌─┐┌┬┐┌─┐┌─┐
╚═╗│ ││ ││││  ║ ║├─┘ ││├─┤ │ ├┤ └─┐
╚═╝└─┘└─┘┘└┘  ╚═╝┴  ─┴┘┴ ┴ ┴ └─┘└─┘
""")
print(" ")
print(" ")
print("""╦  ╦┌─┐┬─┐┌─┐┬┌─┐┌┐┌
╚╗╔╝├┤ ├┬┘└─┐││ ││││
 ╚╝ └─┘┴└─└─┘┴└─┘┘└┘
""")
print("Version: 1.5.7")
print(" ")
print(" ")
print(" ")
print("Please type 1, 2, 3, or 4")
print(" ")
print("[1] GO BACK")
print("||| \-----/")
print(" ")
print("[2] More info")
print("||| \-------/")
print(" ")
print("[3] Contributors")
print("||| \----------/")
print(" ")
print("[4] Start hack")
print("||| \--------/")
choice = input("")

if choice == "1":
    print(" ")
    print("Loading...")
    time.sleep(1)
    print("\n" * 64) 
    from subprocess import call
    call(["python", "main.py"])
    
if choice == "2":
    print(" ")
    print("Loading...")
    time.sleep(1)
    print("\n" * 64) 
    from subprocess import call
    call(["python", "Kahoot/More.py"])
    
if choice == "3":
    print(" ")
    print("Loading...")
    time.sleep(1)
    print("\n" * 64) 
    from subprocess import call
    call(["python", "Kahoot/C.py"])
    
if choice == "4":
    print(" ")
    print("Loading...")
    time.sleep(1)
    print("\n" * 64) 
    from subprocess import call
    call(["python", "Kahoot/kahoot.py"])
